### ISSUE TITLE
Error with initial source run

### ISSUE THREAD

**Issue by adletaw** [jae0/ecomod#2]
Hello,

Thank you for creating this very intricate package!  I am simply helping a friend get started, and there seems to be a bug in the `ecomod.rprofile.r` code [here](https://github.com/jae0/ecomod/blob/master/_ecomodSetup/ecomod.rprofile.r#L8).  The function `is.null` will generate an error if you feed in the name of a variable that does not yet exist.  Instead, I have found it works to use: 

`if(!exists("ecomod.workdirectory")){`.

Otherwise, running `source( file.path(ecomod.directory, "_ecomodSetup", "ecomod.rprofile.r" ))` line will generate this error:

`Error in exists(ecomod.workdirectory) :   object 'ecomod.workdirectory' not found`.

The same applies with other lines where `is.null` was used in that script.  I didn't have errors there because the object already existed.

**Comment by adletaw** [comment]
Hey, thanks for fixing this!

**Comment by jae0** [comment]
Welcome. Thanks for pointing it out.                                                                                                                                                                                                                                                                                                                                                                                                                   From: A.D. LetawSent: Friday, February 12, 2016 2:32 PMTo: jae0/ecomodReply To: jae0/ecomodSubject: Re: [ecomod] Error with initial source run (#2)Hey, thanks for fixing this!

—Reply to this email directly or view it on GitHub.
